version: "3.8"

services:

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - data:/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  data: {}
